neg:
	yasm -f elf64 -g dwarf2 -l negation.lst negation.asm
	ld negation.o -o negation

1:
	yasm -f elf64 -g dwarf2 -l ex1.lst ex1.asm
	ld ex1.o -o ex1

2:
	yasm -f elf64 -g dwarf2 -l ex2.lst ex2.asm
	ld ex2.o -o ex2

3:
	yasm -f elf64 -g dwarf2 -l ex3.lst ex3.asm
	ld ex3.o -o ex3

4:
	yasm -f elf64 -g dwarf2 -l ex4.lst ex4.asm
	ld ex4.o -o ex4

